import Head from "next/head";
import { useEffect } from "react";
import Image from "next/image";
import MainCarousel from "../components/Home/MainCarousel";
import ShoppingList from "../components/Home/ShoppingList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SNEAKER HEAD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MainCarousel /> */}
      <ShoppingList />
    </div>
  );
}
